### ISSUE TITLE
no work for me :D

### ISSUE THREAD

**Issue by ghost** [suyeonme/google-keep-clone#7]
![Untitled](https://user-images.githubusercontent.com/26906261/96658153-74320280-1309-11eb-894e-4fa2d12cc014.png)
![Untitled2](https://user-images.githubusercontent.com/26906261/96658157-75fbc600-1309-11eb-8d35-78125a14dc30.png)
:D

**Comment by hanna-dhkd** [comment]
I updated README.md! I might have omitted a couple of setup things.. :) 
(firebase initial setup and env variable name)

**Comment by suyeonme** [comment]
I updated README.md! I might have omitted a couple of setup things.. :)
(firebase initial setup and env variable name)

**Comment by tkmine** [comment]
![image](https://user-images.githubusercontent.com/26906261/97186844-0b121b00-175f-11eb-8ef5-2b2e39b76979.png)
Thanks! Its work wow :)) ...!

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/26906261/97197568-094e5480-176b-11eb-85e1-ca64e3eb87ca.png)
Thanks! Its work wow :)) ...!

**Comment by suyeonme** [comment]
I am glad to hear that!
